-- Supabase is the only application datastore. Run with the Supabase migration tool.
create extension if not exists pgcrypto;
create table if not exists public.workspaces (id uuid primary key default gen_random_uuid(), owner_user_id uuid not null references auth.users(id) on delete cascade, name text not null, created_at timestamptz not null default now());
create table if not exists public.workspace_members (workspace_id uuid not null references public.workspaces(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, role text not null default 'member' check (role in ('owner','member')), primary key(workspace_id,user_id));
create table if not exists public.credit_accounts (workspace_id uuid primary key references public.workspaces(id) on delete cascade, balance integer not null default 0 check(balance >= 0), updated_at timestamptz not null default now());
create table if not exists public.projects (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces(id) on delete cascade, title text not null, aspect_ratio text not null check(aspect_ratio in ('9:16','16:9','1:1')), duration_seconds integer not null check(duration_seconds = 8), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.generations (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, status text not null default 'queued' check(status in ('queued','submitted','processing','completed','failed','canceled','refunded')), prompt text not null, style text not null default 'cinematic', model text not null, aspect_ratio text not null check(aspect_ratio in ('9:16','16:9','1:1')), duration_seconds integer not null check(duration_seconds = 8), generate_audio boolean not null default true, credits_reserved integer not null check(credits_reserved >= 0), idempotency_key uuid not null unique, provider_job_id text unique, output_url text, error_code text, provider_metadata jsonb, refunded_at timestamptz, created_at timestamptz not null default now(), completed_at timestamptz);
create table if not exists public.credit_ledger (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces(id) on delete cascade, amount integer not null, reason text not null check(reason in ('generation_reservation','generation_refund','purchase','adjustment')), reference_id uuid, created_at timestamptz not null default now(), unique(reason,reference_id));
create index if not exists projects_workspace_created_idx on public.projects(workspace_id, created_at desc);
create index if not exists generations_project_created_idx on public.generations(project_id, created_at desc);

alter table public.workspaces enable row level security; alter table public.workspace_members enable row level security; alter table public.credit_accounts enable row level security; alter table public.projects enable row level security; alter table public.generations enable row level security; alter table public.credit_ledger enable row level security;
create or replace function public.is_workspace_member(p_workspace_id uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from workspace_members where workspace_id=p_workspace_id and user_id=auth.uid())$$;
create policy "members read workspaces" on public.workspaces for select using (public.is_workspace_member(id));
create policy "members read accounts" on public.credit_accounts for select using (public.is_workspace_member(workspace_id));
create policy "members read projects" on public.projects for select using (public.is_workspace_member(workspace_id));
create policy "members read generations" on public.generations for select using (exists(select 1 from projects p where p.id=project_id and public.is_workspace_member(p.workspace_id)));
create policy "members read ledger" on public.credit_ledger for select using (public.is_workspace_member(workspace_id));

create or replace function public.create_project(p_title text,p_aspect_ratio text,p_duration_seconds int) returns uuid language plpgsql security definer set search_path=public as $$declare v_workspace uuid; v_project uuid; begin select workspace_id into v_workspace from workspace_members where user_id=auth.uid() order by role='owner' desc limit 1; if v_workspace is null then raise exception 'NO_WORKSPACE'; end if; insert into projects(workspace_id,title,aspect_ratio,duration_seconds) values(v_workspace,left(trim(p_title),80),p_aspect_ratio,p_duration_seconds) returning id into v_project; return v_project; end $$;
create or replace function public.reserve_generation(p_project_id uuid,p_prompt text,p_style text,p_model text,p_aspect_ratio text,p_duration_seconds int,p_generate_audio boolean,p_credits int,p_idempotency_key uuid) returns table(generation_id uuid,status text,duplicate boolean) language plpgsql security definer set search_path=public as $$declare v_workspace uuid; v_id uuid; v_status text; begin select p.workspace_id into v_workspace from projects p where p.id=p_project_id and public.is_workspace_member(p.workspace_id); if v_workspace is null then raise exception 'FORBIDDEN'; end if; select id,g.status into v_id,v_status from generations g where idempotency_key=p_idempotency_key; if v_id is not null then return query select v_id,v_status,true; return; end if; update credit_accounts set balance=balance-p_credits,updated_at=now() where workspace_id=v_workspace and balance>=p_credits; if not found then raise exception 'INSUFFICIENT_CREDITS'; end if; insert into generations(project_id,prompt,style,model,aspect_ratio,duration_seconds,generate_audio,credits_reserved,idempotency_key) values(p_project_id,p_prompt,p_style,p_model,p_aspect_ratio,p_duration_seconds,p_generate_audio,p_credits,p_idempotency_key) returning id into v_id; insert into credit_ledger(workspace_id,amount,reason,reference_id) values(v_workspace,-p_credits,'generation_reservation',v_id); return query select v_id,'queued'::text,false; end $$;
-- Only service_role may execute these system transitions (never expose them to clients).
create or replace function public.system_mark_generation_submitted(p_generation_id uuid,p_provider_job_id text,p_metadata jsonb default '{}'::jsonb) returns void language plpgsql security definer set search_path=public as $$begin update generations set status='submitted',provider_job_id=p_provider_job_id,provider_metadata=p_metadata where id=p_generation_id and status='queued'; end $$;
create or replace function public.system_apply_provider_update(p_provider_job_id text,p_status text,p_output_url text default null,p_error_code text default null,p_metadata jsonb default '{}'::jsonb) returns void language plpgsql security definer set search_path=public as $$declare v_generation generations%rowtype; v_workspace uuid; begin select g.*,p.workspace_id into v_generation from generations g join projects p on p.id=g.project_id where g.provider_job_id=p_provider_job_id for update; if not found then return; end if; if p_status in ('succeeded','completed') then update generations set status='completed',output_url=p_output_url,provider_metadata=p_metadata,completed_at=now() where id=v_generation.id and status not in ('completed','refunded'); elsif p_status in ('failed','canceled','error') then update generations set status='failed',error_code=coalesce(p_error_code,'PROVIDER_FAILED'),provider_metadata=p_metadata where id=v_generation.id and status not in ('completed','refunded'); if v_generation.refunded_at is null then update credit_accounts set balance=balance+v_generation.credits_reserved,updated_at=now() where workspace_id=v_workspace; insert into credit_ledger(workspace_id,amount,reason,reference_id) values(v_workspace,v_generation.credits_reserved,'generation_refund',v_generation.id) on conflict(reason,reference_id) do nothing; update generations set refunded_at=now(),status='refunded' where id=v_generation.id and refunded_at is null; end if; end if; end $$;
revoke all on function public.system_mark_generation_submitted(uuid,text,jsonb), public.system_apply_provider_update(text,text,text,text,jsonb) from public, anon, authenticated;
grant execute on function public.create_project(text,text,int), public.reserve_generation(uuid,text,text,text,text,int,boolean,int,uuid) to authenticated;
create or replace function public.system_fail_unsubmitted(p_generation_id uuid,p_error_code text) returns void language plpgsql security definer set search_path=public as $$declare v_generation generations%rowtype; v_workspace uuid; begin select g.*,p.workspace_id into v_generation from generations g join projects p on p.id=g.project_id where g.id=p_generation_id for update; if not found or v_generation.refunded_at is not null then return; end if; update credit_accounts set balance=balance+v_generation.credits_reserved,updated_at=now() where workspace_id=v_workspace; insert into credit_ledger(workspace_id,amount,reason,reference_id) values(v_workspace,v_generation.credits_reserved,'generation_refund',v_generation.id) on conflict(reason,reference_id) do nothing; update generations set status='refunded',error_code=p_error_code,refunded_at=now() where id=v_generation.id and refunded_at is null; end $$;
revoke all on function public.system_fail_unsubmitted(uuid,text) from public, anon, authenticated;
-- Provision each Supabase Auth user with a private workspace. Initial balance is zero;
-- credits are only added by a trusted purchase/administration flow.
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$declare v_workspace uuid:=gen_random_uuid(); begin insert into public.workspaces(id,owner_user_id,name) values(v_workspace,new.id,coalesce(new.raw_user_meta_data->>'full_name','My workspace')); insert into public.workspace_members(workspace_id,user_id,role) values(v_workspace,new.id,'owner'); insert into public.credit_accounts(workspace_id,balance) values(v_workspace,0); return new; end $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
